name: movies_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  dio: ^5.4.2+1
  pretty_dio_logger: ^1.3.1
  infinite_scroll_pagination: ^4.0.0
  flutter_spinkit: ^5.2.1
  easy_debounce: ^2.0.3
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  youtube_data_api: ^1.0.4
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Black.ttf
